services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins_home:/var/jenkins_home
    expose:
      - 2376
    command:
      - "--insecure-registry=192.168.56.3"
      - "--storage-driver"
      - "overlay2"
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    build:
      context: ../
      dockerfile: ./jenkins/Dockerfile
    # image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
    restart: unless-stopped
    depends_on:
      - jenkins-docker
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins
